"""Default catalog seed — mirrors apps/web loan-products/mock-data.ts."""

from __future__ import annotations

from typing import Any

SEED_GROUPS: list[dict[str, Any]] = [
    {
        "id": "vay-nha",
        "name": "Vay nhà ở",
        "description": "Các sản phẩm vay phục vụ mua, xây dựng, sửa chữa và hoàn thiện nhà ở.",
        "icon_name": "Home",
        "is_active": True,
        "display_order": 1,
    },
    {
        "id": "vay-oto",
        "name": "Vay mua ô tô",
        "description": "Các sản phẩm tài trợ nhu cầu mua ô tô phục vụ sinh hoạt hoặc kinh doanh.",
        "icon_name": "Car",
        "is_active": True,
        "display_order": 2,
    },
    {
        "id": "vay-kinh-doanh",
        "name": "Vay sản xuất kinh doanh",
        "description": "Các sản phẩm vay bổ sung vốn lưu động và phục vụ hoạt động kinh doanh của khách hàng cá nhân.",
        "icon_name": "Briefcase",
        "is_active": True,
        "display_order": 3,
    },
    {
        "id": "vay-tieu-dung",
        "name": "Vay tiêu dùng",
        "description": "Các sản phẩm vay phục vụ nhu cầu tiêu dùng hợp pháp của khách hàng.",
        "icon_name": "ShoppingBag",
        "is_active": True,
        "display_order": 4,
    },
    {
        "id": "vay-hoc-tap",
        "name": "Vay phục vụ học tập",
        "description": "Các sản phẩm hỗ trợ chi phí học tập trong nước và nước ngoài.",
        "icon_name": "GraduationCap",
        "is_active": True,
        "display_order": 5,
    },
    {
        "id": "vay-cam-co",
        "name": "Vay cầm cố tài sản",
        "description": "Các sản phẩm vay được bảo đảm bằng tiền gửi, sổ tiết kiệm hoặc tài sản tài chính.",
        "icon_name": "Key",
        "is_active": True,
        "display_order": 6,
    },
]

# product_code is the stable business key; id is derived at seed time.
SEED_PRODUCTS: list[dict[str, Any]] = [
    {
        "product_code": "IND_HOME_01",
        "product_group_id": "vay-nha",
        "product_name": "Vay mua nhà đất thổ cư",
        "loan_method": "Cho vay từng lần",
        "secured_type": "SECURED",
        "min_amount": 500_000_000,
        "max_amount": 15_000_000_000,
        "min_term": 12,
        "max_term": 300,
        "status": "ACTIVE",
        "interest_rate": 6.9,
        "segments": ["Khách hàng cá nhân phổ thông", "Người nhận lương"],
        "purpose": "Mua nhà đất thổ cư",
        "agent_product_id": "loan-1",
        "channels": ["Tại quầy", "Website", "Ứng dụng"],
    },
    {
        "product_code": "IND_HOME_02",
        "product_group_id": "vay-nha",
        "product_name": "Vay mua nhà dự án",
        "loan_method": "Cho vay trả góp",
        "secured_type": "SECURED",
        "min_amount": 200_000_000,
        "max_amount": 20_000_000_000,
        "min_term": 12,
        "max_term": 420,
        "status": "DRAFT",
        "interest_rate": 7.2,
        "segments": ["Khách hàng cá nhân phổ thông", "Khách hàng ưu tiên"],
        "purpose": "Mua nhà dự án chung cư/biệt thự",
        "agent_product_id": "loan-2",
    },
    {
        "product_code": "IND_HOME_03",
        "product_group_id": "vay-nha",
        "product_name": "Vay xây dựng và sửa chữa nhà",
        "loan_method": "Cho vay trả góp",
        "secured_type": "SECURED",
        "min_amount": 50_000_000,
        "max_amount": 5_000_000_000,
        "min_term": 12,
        "max_term": 180,
        "status": "SUSPENDED",
        "interest_rate": 7.5,
        "segments": ["Khách hàng cá nhân phổ thông", "Người tự doanh"],
        "purpose": "Xây dựng, cải tạo và sửa chữa nhà ở",
        "agent_product_id": "loan-house-repair",
    },
    {
        "product_code": "IND_CAR_01",
        "product_group_id": "vay-oto",
        "product_name": "Vay mua ô tô mới",
        "loan_method": "Cho vay trả góp",
        "secured_type": "SECURED",
        "min_amount": 100_000_000,
        "max_amount": 5_000_000_000,
        "min_term": 12,
        "max_term": 96,
        "status": "ACTIVE",
        "interest_rate": 7.9,
        "segments": ["Khách hàng cá nhân phổ thông", "Người nhận lương", "Người tự doanh"],
        "purpose": "Mua xe ô tô mới phục vụ đi lại hoặc kinh doanh",
        "agent_product_id": "loan-5",
    },
    {
        "product_code": "IND_CAR_02",
        "product_group_id": "vay-oto",
        "product_name": "Vay mua ô tô đã qua sử dụng",
        "loan_method": "Cho vay trả góp",
        "secured_type": "SECURED",
        "min_amount": 80_000_000,
        "max_amount": 2_000_000_000,
        "min_term": 12,
        "max_term": 72,
        "status": "ACTIVE",
        "interest_rate": 8.5,
        "segments": ["Khách hàng cá nhân phổ thông", "Hộ kinh doanh"],
        "purpose": "Mua ô tô cũ đã qua sử dụng",
        "agent_product_id": "loan-5",
    },
    {
        "product_code": "IND_BIZ_01",
        "product_group_id": "vay-kinh-doanh",
        "product_name": "Vay bổ sung vốn kinh doanh thường xuyên",
        "loan_method": "Cho vay hạn mức",
        "secured_type": "SECURED",
        "min_amount": 50_000_000,
        "max_amount": 10_000_000_000,
        "min_term": 6,
        "max_term": 12,
        "status": "ACTIVE",
        "interest_rate": 6.5,
        "segments": ["Hộ kinh doanh", "Cá nhân có hoạt động sản xuất kinh doanh"],
        "purpose": "Bổ sung vốn lưu động sản xuất kinh doanh",
    },
    {
        "product_code": "IND_CONSUME_01",
        "product_group_id": "vay-tieu-dung",
        "product_name": "Vay tiêu dùng có tài sản bảo đảm",
        "loan_method": "Cho vay trả góp",
        "secured_type": "SECURED",
        "min_amount": 50_000_000,
        "max_amount": 3_000_000_000,
        "min_term": 12,
        "max_term": 120,
        "status": "ACTIVE",
        "interest_rate": 8.9,
        "segments": ["Khách hàng cá nhân phổ thông", "Người nhận lương", "Người tự doanh"],
        "purpose": "Tiêu dùng cá nhân phục vụ đời sống",
        "agent_product_id": "loan-3",
    },
    {
        "product_code": "IND_STUDY_01",
        "product_group_id": "vay-hoc-tap",
        "product_name": "Vay du học",
        "loan_method": "Cho vay trả góp",
        "secured_type": "SECURED",
        "min_amount": 50_000_000,
        "max_amount": 2_500_000_000,
        "min_term": 12,
        "max_term": 120,
        "status": "ACTIVE",
        "interest_rate": 7.0,
        "segments": ["Khách hàng cá nhân phổ thông"],
        "purpose": "Thanh toán học phí và chi phí du học nước ngoài",
        "agent_product_id": "loan-4",
    },
    {
        "product_code": "IND_COLLATERAL_01",
        "product_group_id": "vay-cam-co",
        "product_name": "Vay cầm cố sổ tiết kiệm",
        "loan_method": "Cho vay hạn mức",
        "secured_type": "SECURED",
        "min_amount": 10_000_000,
        "max_amount": 50_000_000_000,
        "min_term": 1,
        "max_term": 12,
        "status": "ACTIVE",
        "interest_rate": 5.5,
        "segments": ["Khách hàng cá nhân phổ thông", "Khách hàng ưu tiên", "Hộ kinh doanh"],
        "purpose": "Cầm cố sổ tiết kiệm mở tại SHB hoặc tổ chức tín dụng khác",
    },
    {
        "product_code": "IND_CONS_UNSECURED_01",
        "product_group_id": "vay-tieu-dung",
        "product_name": "Vay tiêu dùng không tài sản bảo đảm",
        "short_name": "Vay tiêu dùng tín chấp",
        "loan_method": "Cho vay theo món / hạn mức tín dụng",
        "secured_type": "UNSECURED",
        "min_amount": 0,
        "max_amount": 500_000_000,
        "min_term": 0,
        "max_term": 60,
        "status": "ACTIVE",
        "interest_rate": 0,
        # Labels must match admin form SEGMENTS checklist
        "segments": ["Khách hàng cá nhân phổ thông", "Người nhận lương"],
        "purpose": "Phục vụ các nhu cầu tiêu dùng của khách hàng",
        "agent_product_id": "retail_unsecured_salary",
        "channels": ["Tại quầy", "Website", "Ứng dụng"],
        "loan_structure": {
            "minAmount": None,
            "maxAmount": 500_000_000,
            "minTermMonths": None,
            "maxTermMonths": 60,
            "creditMethods": ["TERM_LOAN", "CREDIT_LIMIT"],
            "loanMethodName": "Cho vay theo món / hạn mức tín dụng",
            "securedTypeName": "Không có tài sản bảo đảm",
        },
        "interest_config": {
            "publishedRate": None,
            "promoRate": None,
            "displayText": "Theo chính sách từ SHB",
        },
        "repayment_config": {
            "method": "Theo thỏa thuận và chính sách SHB từng thời kỳ",
        },
        "eligibility": {
            "nationality": "VIETNAMESE",
            "customerTypes": ["INDIVIDUAL", "HOUSEHOLD"],
            "minimumAgeAtApplication": 22,
            "maximumAgeAtMaturity": 70,
            "stableIncomeRequired": True,
            "goodCreditHistoryRequired": True,
            "repaymentCapacityProofRequired": True,
        },
        "document_groups": [
            {
                "title": "Hồ sơ pháp lý",
                "items": [
                    "CCCD còn hiệu lực",
                    "Thông tin cư trú",
                    "Giấy tờ chứng minh mối quan hệ (nếu có)",
                ],
                "code": "LEGAL_DOCUMENTS",
                "name": "Hồ sơ pháp lý",
                "required": True,
            },
            {
                "title": "Hồ sơ chứng minh thu nhập trả nợ",
                "items": [
                    "Hợp đồng lao động",
                    "Sao kê lương 3 tháng gần nhất",
                    "Xác nhận thu nhập khác (nếu có)",
                ],
                "code": "INCOME_DOCUMENTS",
                "name": "Hồ sơ chứng minh thu nhập trả nợ",
                "required": True,
            },
            {
                "title": "Hồ sơ chứng minh mục đích vay vốn",
                "items": [
                    "Phương án sử dụng vốn kiêm cam kết trả nợ",
                    "Giấy đề nghị vay vốn kiêm phương án trả nợ",
                ],
                "code": "LOAN_PURPOSE_DOCUMENTS",
                "name": "Hồ sơ chứng minh mục đích vay vốn",
                "required": True,
            },
        ],
    },
]
