"""Seed dossier payloads for application-svc (demo + CCCD cards).

Idempotent by applicant.id_number. Loan/phone/income not on CCCD are plausible demo fills.
"""

from __future__ import annotations

from datetime import date
from decimal import Decimal
from typing import Any


def _addr(
    street: str,
    *,
    ward: str | None = None,
    district: str | None = None,
    province: str | None = None,
    kind: str = "permanent",
) -> dict[str, Any]:
    return {
        "kind": kind,
        "street": street,
        "ward": ward,
        "district": district,
        "province": province,
        "same_as_permanent": kind == "current",
    }


def _base(
    *,
    scenario: str,
    product: str,
    amount: int,
    term_months: int,
    full_name: str,
    id_number: str,
    dob: date,
    gender: str,
    id_issue_date: date | None,
    id_issue_place: str,
    permanent: dict[str, Any],
    current: dict[str, Any] | None = None,
    phone: str,
    email: str,
    income: int,
    expense: int,
    purpose_detail: str,
    occupation: str,
    employer: str,
    position: str,
    work_address: str,
    branch: str,
    account_no: str,
    docs: list[dict[str, Any]],
) -> dict[str, Any]:
    addresses = [permanent]
    if current:
        addresses.append(current)
    else:
        addresses.append({**permanent, "kind": "current", "same_as_permanent": True})
    return {
        "scenario": scenario,
        "product": product,
        "total_amount": Decimal(amount),
        "term_months": term_months,
        "lending_method": "per_loan",
        "status": "submitted",
        "applicant": {
            "customer_id": None,
            "full_name": full_name,
            "dob": dob,
            "gender": gender,
            "id_number": id_number,
            "id_issue_date": id_issue_date,
            "id_issue_place": id_issue_place,
            "email": email,
        },
        "phone": {"mobile_1": phone, "zalo_phone": phone},
        "addresses": addresses,
        "employment": {
            "occupation": occupation,
            "employer_name": employer,
            "position": position,
            "work_address": work_address,
            "salary_day": "5",
        },
        "references": [
            {
                "seq": 1,
                "full_name": f"Người thân của {full_name.split()[-1]}",
                "relationship": "Người thân",
                "phone": phone[:-1] + "1" if phone else "0900000001",
                "same_address": True,
            }
        ],
        "financial": {
            "total_income": Decimal(income),
            "personal_expense": Decimal(expense),
        },
        "consent": {
            "data_processing_consent": True,
            "marketing_consent": True,
            "consent_version": "seed-2026-07",
        },
        "purposes": [
            {
                "category": "consumer",
                "amount": Decimal(amount),
                "purpose_detail": purpose_detail,
                "goods": [],
            }
        ],
        "disbursements": [
            {
                "for_category": "consumer",
                "method": "borrower",
                "bank": "SHB",
                "branch": branch,
                "account_no": account_no,
                "account_name": full_name,
            }
        ],
        "documents": docs,
    }


SEED_DOSSIERS: list[dict[str, Any]] = [
    # --- 3 demo wow-flow (UI assess-dashboard) ---
    _base(
        scenario="demo_happy",
        product="retail_unsecured_salary",
        amount=150_000_000,
        term_months=36,
        full_name="NGUYỄN THỊ BÉ HOA",
        id_number="074300004128",
        dob=date(2000, 6, 10),
        gender="nu",
        id_issue_date=date(2025, 5, 21),
        id_issue_place="Bộ Công an",
        permanent=_addr(
            "Tổ 2, Khu Phố Cổng Xanh, Tân Bình, Bắc Tân Uyên",
            province="Bình Dương",
        ),
        phone="0912300004",
        email="behoa.nguyen@email.com",
        income=22_000_000,
        expense=8_000_000,
        purpose_detail="mua_sam",
        occupation="cong_chuc",
        employer="Công ty TNHH SX TM Phúc Thịnh",
        position="nhan_vien",
        work_address="Khu công nghiệp VSIP II, Bình Dương",
        branch="Chi nhánh Bình Dương",
        account_no="104074300004",
        docs=[
            {"doc_type": "cccd", "title": "CCCD", "status": "verified", "tier": 1},
            {"doc_type": "sao_ke_luong", "title": "Sao kê lương", "status": "verified", "tier": 1},
            {"doc_type": "cic", "title": "CIC", "status": "verified", "tier": 1},
        ],
    ),
    _base(
        scenario="demo_veto",
        product="retail_unsecured_salary",
        amount=160_000_000,  # ≤12× income 18tr so purpose veto is the only block
        term_months=24,
        full_name="TRẦN THỊ VUI",
        id_number="091185013867",
        dob=date(1985, 5, 10),
        gender="nu",
        id_issue_date=date(2023, 6, 2),
        id_issue_place="Cục Cảnh sát QLHC về TTXH",
        permanent=_addr("Mong Thá, Châu Thành", province="Kiên Giang"),
        current=_addr("Thổ Sơn, Hòn Đất", province="Kiên Giang", kind="current"),
        phone="0913000091",
        email="vui.tran@email.com",
        income=18_000_000,
        expense=10_000_000,
        purpose_detail="tieu_dung",
        occupation="tu_doanh",
        employer="Hộ kinh doanh cá thể",
        position="khac",
        work_address="Chợ Thổ Sơn, Hòn Đất, Kiên Giang",
        branch="Chi nhánh Kiên Giang",
        account_no="109091185013",
        docs=[
            {"doc_type": "cccd", "title": "CCCD", "status": "verified", "tier": 1},
            {"doc_type": "sao_ke_luong", "title": "Sao kê lương", "status": "uploaded", "tier": 1},
            {"doc_type": "cic", "title": "CIC", "status": "verified", "tier": 1},
            {
                "doc_type": "purpose_evidence",
                "title": "Chứng từ mục đích",
                "status": "uploaded",
                "tier": 2,
            },
        ],
    ),
    _base(
        scenario="demo_hitl",
        product="retail_unsecured_salary",
        amount=180_000_000,  # ≤12× income 15tr; CIC group 2 → HITL
        term_months=48,
        full_name="NGUYỄN THỊ HUYỀN TRẦN",
        id_number="054301008970",
        dob=date(2001, 3, 19),
        gender="nu",
        id_issue_date=date(2022, 7, 5),
        id_issue_place="Cục Cảnh sát QLHC về TTXH",
        permanent=_addr("Hiệp Trung, Thị xã Đông Hòa", province="Phú Yên"),
        current=_addr(
            "Khu Phố Phú Hòa, Hòa Hiệp Trung, Thị xã Đông Hòa",
            province="Phú Yên",
            kind="current",
        ),
        phone="0905400054",
        email="huyentran.nguyen@email.com",
        income=15_000_000,
        expense=7_000_000,
        purpose_detail="sua_nha",
        occupation="cong_chuc",
        employer="Trường THCS Hòa Hiệp Trung",
        position="nhan_vien",
        work_address="Thị xã Đông Hòa, Phú Yên",
        branch="Chi nhánh Phú Yên",
        account_no="105054301008",
        docs=[
            {"doc_type": "cccd", "title": "CCCD", "status": "verified", "tier": 1},
            {"doc_type": "sao_ke_luong", "title": "Sao kê lương", "status": "uploaded", "tier": 2},
            {"doc_type": "cic", "title": "CIC", "status": "verified", "tier": 1},
        ],
    ),
    # --- 4 CCCD mới ---
    _base(
        scenario="cccd_dang_thi_trang",
        product="retail_unsecured_salary",
        amount=120_000_000,
        term_months=36,
        full_name="ĐẶNG THỊ TRẮNG",
        id_number="096193000296",
        dob=date(1993, 11, 15),
        gender="nu",
        id_issue_date=date(2021, 4, 9),
        id_issue_place="Cục Cảnh sát QLHC về TTXH",
        permanent=_addr(
            "Khóm 7, Thị Trấn Năm Căn, Năm Căn",
            province="Cà Mau",
        ),
        phone="0961930296",
        email="trang.dang@email.com",
        income=16_000_000,
        expense=6_000_000,
        purpose_detail="tieu_dung",
        occupation="nhan_vien",
        employer="Công ty TNHH Thương mại Cà Mau",
        position="nhan_vien",
        work_address="Thị trấn Năm Căn, Cà Mau",
        branch="Chi nhánh Cà Mau",
        account_no="109619300029",
        docs=[
            {"doc_type": "cccd", "title": "CCCD", "status": "verified", "tier": 1},
            {"doc_type": "sao_ke_luong", "title": "Sao kê lương", "status": "uploaded", "tier": 1},
            {"doc_type": "cic", "title": "CIC", "status": "verified", "tier": 1},
        ],
    ),
    _base(
        scenario="cccd_nguyen_quoc_viet",
        product="retail_unsecured_salary",
        amount=180_000_000,
        term_months=48,
        full_name="NGUYỄN QUỐC VIỆT",
        id_number="095081010451",
        dob=date(1981, 1, 1),
        gender="nam",
        id_issue_date=date(2021, 5, 12),
        id_issue_place="Cục Cảnh sát QLHC về TTXH",
        permanent=_addr(
            "Ấp Huê I, Vĩnh Phú Tây, Phước Long",
            province="Bạc Liêu",
        ),
        phone="0950810451",
        email="viet.nguyen@email.com",
        income=20_000_000,
        expense=7_500_000,
        purpose_detail="phuong_tien",
        occupation="tu_doanh",
        employer="Hộ kinh doanh Nguyễn Quốc Việt",
        position="khac",
        work_address="Vĩnh Phú Tây, Phước Long, Bạc Liêu",
        branch="Chi nhánh Bạc Liêu",
        account_no="109508101045",
        docs=[
            {"doc_type": "cccd", "title": "CCCD", "status": "verified", "tier": 1},
            {"doc_type": "sao_ke_luong", "title": "Sao kê lương", "status": "uploaded", "tier": 1},
            {"doc_type": "cic", "title": "CIC", "status": "verified", "tier": 1},
        ],
    ),
    _base(
        scenario="cccd_nguyen_minh_quen",
        product="retail_mortgage",
        amount=800_000_000,
        term_months=180,
        full_name="NGUYỄN MINH QUEN",
        id_number="089085006905",
        dob=date(1985, 12, 20),
        gender="nam",
        id_issue_date=date(2021, 9, 16),
        id_issue_place="Bộ Công an",
        permanent=_addr(
            "Tổ 4, Ấp Hiệp Thuận, Bình Thạnh Đông",
            province="An Giang",
        ),
        phone="0890856905",
        email="quen.nguyen@email.com",
        income=25_000_000,
        expense=9_000_000,
        purpose_detail="mua_nha",
        occupation="can_bo_dn",
        employer="Công ty CP Xây dựng An Giang",
        position="can_bo_ql",
        work_address="Long Xuyên, An Giang",
        branch="Chi nhánh An Giang",
        account_no="108908500690",
        docs=[
            {"doc_type": "cccd", "title": "CCCD", "status": "verified", "tier": 1},
            {"doc_type": "sao_ke_luong", "title": "Sao kê lương", "status": "uploaded", "tier": 1},
            {"doc_type": "so_do", "title": "Sổ đỏ", "status": "uploaded", "tier": 1},
            {"doc_type": "cic", "title": "CIC", "status": "verified", "tier": 1},
        ],
    ),
    _base(
        scenario="cccd_tran_thi_hong_phuc",
        product="retail_unsecured_salary",
        amount=100_000_000,
        term_months=24,
        full_name="TRẦN THỊ HỒNG PHÚC",
        id_number="066192009555",
        dob=date(1992, 8, 26),
        gender="nu",
        id_issue_date=date(2021, 8, 9),
        id_issue_place="Cục Cảnh sát QLHC về TTXH",
        permanent=_addr(
            "Thôn 2, Ea KPam, Cư M'gar",
            province="Đắk Lắk",
        ),
        phone="0661929555",
        email="hongphuc.tran@email.com",
        income=14_000_000,
        expense=5_500_000,
        purpose_detail="tieu_dung",
        occupation="cong_chuc",
        employer="UBND xã Ea KPam",
        position="nhan_vien",
        work_address="Ea KPam, Cư M'gar, Đắk Lắk",
        branch="Chi nhánh Đắk Lắk",
        account_no="106619200955",
        docs=[
            {"doc_type": "cccd", "title": "CCCD", "status": "verified", "tier": 1},
            {"doc_type": "sao_ke_luong", "title": "Sao kê lương", "status": "uploaded", "tier": 1},
            {"doc_type": "cic", "title": "CIC", "status": "verified", "tier": 1},
        ],
    ),
]
